name: Deploy Python App to Vercel

env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Configuration
        run: vercel pull --yes --environment=development --token=${{secrets.VERCEL_TOKEN}}

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{secrets.VERCEL_TOKEN}}
